### PR TITLE
Community - Toggle dark/light theme on the body tag

### LINKED ISSUE #2758: there is a white "tray" at the bottom of the post page in dark mode
screen shot 2018-04-25 at 09 58 14

### PR DESCRIPTION
**Pull request by roadscape**
From @quochuy #3334:

> This hides the empty spaces created by a hidden element [at the bottom of pages]

Closes #2758

### CODE REVIEW

**Comment by roadscape** [comment]
Tested working

**Comment by roadscape** [comment]
@quochuy there is an error when rendering from server: `ReferenceError: document is not defined` -- could you pls take a look?

**Comment by quochuy** [comment]
@roadscape I think I know why. Will fix that

**Comment by quochuy** [comment]
@roadscape how do I trigger a render from server for testing?

**Comment by roadscape** [comment]
Works great now 👍

**Pull request merged**
