### PR TITLE
#1535 linted more app components

### PR DESCRIPTION
**Pull request by NateBrune**

### CODE REVIEW

**Comment by goldibex** [comment]
@NateBrune unfortunately some merge conflicts have arisen, can you clear those and push again?

**Comment by bnchdrff** [comment]
what linting rules were used to format these files? how much work is it to apply them to all our components at once & enforce them for all future PRs?

**Comment by relativityboy** [comment]
After resolving merge conflicts, htmlready tests were failing. 
```
htmlready should return plain text without html unmolested:
     TypeError: Cannot read property 'prefix' of null
      at Document.nodeSerializeToString [as toString] (node_modules/xmldom/dom.js:920:22)
      at XMLSerializer.serializeToString (node_modules/xmldom/dom.js:914:31)
      at exports.default (src/shared/HtmlReady.js:102:45)
      at Context.<anonymous> (src/shared/HtmlReady.test.js:17:19)
```

The style of this pr doesn't conform to our current linting rules. If the CI check fails on the merge push, I'm closing this PR without merging. Updates to linting should be done as part of the development process, or a new branch can be created if there's a desire to work on it.

**Comment by relativityboy** [comment]
CI tests are passing, and master is also throwing a caught-but-logged _'prefix' of null_ error in the same spot. Merging.

**Pull request merged**
