### PR TITLE
Community - Use steemscript to format canonical URLs

### LINKED ISSUE #336: Proposal: canonical links and json_metadata
If you'd rather I take this to steemit.com for a discussion, I'm more than happy to start up a post. I figured a simple agreement here though may be easy enough. 

I'm proposing a simple change to the way that steemit.com generates it's canonical links, to establish a standard use case of SEO for non-steemit.com websites that are powered by the steem blockchain. The change within this codebase would be simple:

> By default on each comment, steemit.com generates the canonical link meta tag as normal. However, if within the `json_metadata` field the `canonical` property is set, it will use that value in place of the steemit.com domain.

This would become a best practice for anyone developing a website displaying user generated content from the steem blockchain.

For example, I created a post in with the tag #steemws, titled `steem.ws - The public steem api cluster`. By default, when viewing the post on steemit.com, the canonical link included into the content would be:

`https://steemit.com/steemws/@jesta/steem-ws-the-public-steem-api-cluster`

However, if when this post was created, I set the `canonical` field within `json_metadata` to `http://jesta.us`, when viewing the post on steemit.com the canonical link would now be:

`http://jesta.us/steemws/@jesta/steem-ws-the-public-steem-api-cluster`

This will let content creators specify the origin of their content and control a bit of it's SEO. Bots  could also use this to avoid accidentally flagging original content as plagiarism. This concept could also be further expanded to other SEO criteria, but I feel the canonical link is the most important of the bunch, especially with this content technically being available for any website. 

I am not asking for steemit.com to allow for the addition or modification of this data, and by default, all canonical links should default to steemit.com. However, if using an external tool (such as a CMS build on steem for running a custom website) I'd expect the tool to automatically append this data to any posts created from that website. 

Is this a reasonable request? If so, I'll put forth the effort and issue a pull request.

### PR DESCRIPTION
**Pull request by roadscape**
Replaces #2947 by @Smittyvb:

> Closes #336. Now canonical URLs are formatted according to [steemscript](https://github.com/bonuschain/steemscript) rules.

### CODE REVIEW

**Comment by roadscape** [comment]
Steemscript diff shows that v1.0.2 tag on github does not include a version bump commit: 
https://github.com/bonuschain/steemscript/compare/v1.0.0...v1.0.2

`master` reports as 1.0.2 but includes more changes to review:
https://github.com/bonuschain/steemscript/compare/v1.0.0...master

**Comment by roadscape** [comment]
@Smittyvb could you reach out to the maintainers wrt the discrepancy above?

**Comment by Smittyvb** [comment]
It appears the version on NPM is the real 1.0.2. The master branch of steemscript has changes, but they have not yet been released.

**Comment by roadscape** [comment]
@Smittyvb thank you, one last thing -- would you mind putting the logic into its own method and adding a couple simple tests? Example tests can be found in `condenser/src/app/utils/`.

**Comment by roadscape** [comment]
Excellent, thanks for the contrib @Smittyvb!

**Comment by gansbrest** [comment]
I've been reading through a bunch of PRs and it seems like the current solution is only applicable to "apps", meaning platform aggregators that generate content for other users (like Medium for example).

How about regular use case, where I have a blog on my own domain example.com where I publish posts and distribute them via different means (plugins) to other platforms like steemit?

Each post on example.com would have simple blog urls like example.com/my-post-url (note, there are no users or categories) which suppose to be canonical url on external platforms like steemit.

I'm sure there are a ton of blogs like that that would like to distribute their content and use proper canonical links. 

Have you consider those? What's the approach we should take for regular blogs/sites? Should we submit PR for apps.js steemscript for each blog (would get out of hands pretty quickly)?

Please advice.

**Comment by gansbrest-hbo** [comment]
@Smittyvb could you elaborate a bit more please (show example). Is this json_metadata.canonical suppose to be part of post data, or is that common json_metadata field that stores everything.

It seems like it makes sense to pass canonical url along with the post itself in addition to "account" level.

Also when you say set canonical to blog post URL, do you mean specific post or some common base url?

**Comment by gansbrest** [comment]
@Smittyvb could you elaborate a bit more please (show example). Is this json_metadata.canonical suppose to be part of post data, or is that common json_metadata field that stores everything.

It seems like it makes sense to pass canonical url along with the post itself in addition to "account" level, so individual post could overwrite defaults on the account, but I'm not sure how post are currently stored on steemit honestly..

Also when you say set canonical to blog post URL, do you mean specific post or some common base url?

**Comment by Smittyvb** [comment]
@gansbrest

> json_metadata 

Steem posts can have additional data beyond the body and title. For instance, tags. This is called the JSON metadata. You can put whatever data you want there, and it won't usually get displayed. Some things that are stored here:
- Tags
- App used to create the post
- The post format
- Images in the post

This could also store a custom canonical URL for the post. Currently you can't easily set custom values for the JSON metadata. It might be added to Steemit in the future. But if you use the CLI, or use an API, you can set the JSON metadata. 

> "account" level

That's a good idea, but it would require an additional request to load account level data for each post request, which we want to avoid. With unlimited post editing, just setting a canonical URL for each individual post should work.

> Also when you say set canonical to blog post URL, do you mean specific post or some common base url?

Blog post URL.

> show example

So when you make a post on your Example.com blog, you'd post the post on your Example.com blog, with a URL of ``http://example.com/a-post``. Then, you'd post it on the blockchain, with the ``canonical`` key of the JSON metadata being ``http://example.com/a-post``.

**Comment by gansbrest** [comment]
Thanks a lot for the clarifications @Smittyvb 

Biggest question I have at the moment - if I add `canonical: [link]` property to post metadata (somehow, cli or api) would it override default canonical link tag on the Steemit.com website? 

In you previous post you mentioned that it's not supported, by that you meant there is no easy way to access it through UI or it this post `json_metadata.canonical` property is not used for <link> tag generation on steemit?

Could you please provide super simple example of the api / cli call that updates metadata with canonical property if you have time. I'm sure it would be super useful for a lot of people.

**Comment by talhasch** [comment]
the pr you referred doesn't explains clearly usage of this case. lets wait until this type of usage matured.

**Pull request merged**
