### PR TITLE
Quochuy notification filters

### PR DESCRIPTION
**Pull request by gl2748**
In organization version of: https://github.com/steemit/condenser/pull/3734

### CODE REVIEW

**Comment by gl2748** [comment]
@quochuy i agree with this in principle. One change to be made is that the filters appear in a block of code with the following condition:

https://github.com/steemit/condenser/pull/3743/files#diff-83c21b84327f6fc7bb2d1fe315663e50R258

Which means the filters will not appear when there are no unread notifications. I suggest putting the filters outside this condition, as it pertains to the 'mark as read' button alone.

**Comment by quochuy** [comment]
@gl2748
Will have a look soon

**Comment by Benson0224** [comment]
@gl2748  is this PR still valid? if yes please help to merge it, thanks

**Comment by gl2748** [comment]
@Benson0224 yes, still valid, please review.

**Pull request merged**
