### PR TITLE
Add new Chinese translations

### PR DESCRIPTION
**Pull request by originated**

### CODE REVIEW

**Comment by bnchdrff** [comment]
@originated do we want to add a chinese option to the menu?

**Comment by skenan** [comment]
@bnchdrff  @originated  I am sure the one you merged didn't test in production. It doesn't handle the plurals. The PR #1866 I created has been there for 2 months and was tested in my https://cnsteem.com. Don't know why you merge this one..

**Comment by originated** [comment]
@bnchdrff Nope let's not add to the quite yet to the menu, going to address @skenan items. @skenan can you please join our translation system we have a unified area for translators.  Please email translate@steemit.com

**Comment by skenan** [comment]
@originated Sure.

**Pull request merged**
