### PR TITLE
Fix, display total votes in post summary, refs #1596

### PR DESCRIPTION
**Pull request by gl2748**
Refs #1596

### Before.
screenshot from 2017-08-08 08-14-18

### After.
screenshot from 2017-08-08 08-59-00

This is a naive fix, that uses the existing vote-count from the `Voting` component rather than the `VotesAndComments` component. It might be worth considering consolidating these two components.

Anyway I was wondering if anyone @valzav, @roadscape @TheIntrnet could tell me where [`net_votes`](https://github.com/steemit/condenser/blob/master/src/app/components/elements/VotesAndComments.jsx#L51) is coming from? As setting this up correctly would perhaps be the ideal solution.

### CODE REVIEW

**Comment by gl2748** [comment]
@sneak, does the style change with this approach pass muster? See the b4 and after screen caps above ...

**Comment by sneak** [comment]
yeah the vote count in the post list view should not have a dropdown / menu reveal chevron. it should not be clickable at all.

**Comment by gl2748** [comment]
@valzav implemented solution as you suggested.

**Comment by valzav** [comment]
@gl2748, can I ask you to make one more change: please instead of post_obj pass total_votes into the component - it will let shouldComponentUpdate to detect real changes in props and not re-render if something has changed in post obj not related to votes count.

**Comment by roadscape** [comment]
@gl2748 Please rebase, let's test and merge asap.

**Pull request merged**
