### PR TITLE
Community - fix overlapping header

### LINKED ISSUE #3281: Content near top of screen is sometimes obscured
Observed Behavior:
Some pages load with their top-most content obscured by the header/ad bar.

Expected Behavior:
Any content at the top of a page should be visible below the header/ad bar.

Reproduction:
1. Load a user's profile such as: https://steemit.com/@justinw
2. Perform several non-cache-busting page reloads until the content is obscured (e.g. ctrl/cmd+r)

Additional Info:
1. Performing a cache-busting page reload seems to always result in the proper layout with no obscured content. (e.g. ctrl/cmd+shift+r)

Screenshots:
image

### PR DESCRIPTION
**Pull request by roadscape**
From @quochuy #3377:

> Fixes #3281 - Replacing 'slotRenderEnded' with 'impressionViewable' to resize the header only when the ad is visible.
>
> I can't seem to get ads to work on my dev environment so help testing this would be appreciated.
>
> I wanted to test this solution:
> https://stackoverflow.com/questions/35025046/the-exact-moment-of-gpt-viewability-vs-slotrenderended-event-fired

### CODE REVIEW

**Comment by roadscape** [comment]
Hi @quochuy, not sure if you're available right now but the branch `quochuy-header_height_with_ads` is now deployed to https://steemitdev.com for testing.

**Comment by quochuy** [comment]
@roadscape thank you. https://steemitdev.com/ is getting a 503 error.

**Comment by roadscape** [comment]
@quochuy ah the environment goes down for a few hours every day. But I'll get some feedback on #3390 as it may end up resolving the original issue.

**Comment by roadscape** [comment]
Ok, it sounds like this change has already been tried and didn't resolve the issue. The merge of #3390 would require re-evaluating the approach, so let's close this for now. It's possible we may have to ditch the floating header.

**Pull request closed without merging**
