### PR TITLE
add Japanese language

### PR DESCRIPTION
**Pull request by inoue-a**
Please add Japanese to locales.

### CODE REVIEW

**Comment by originated** [comment]
@bnchdrff This is ready to be merged for the additional language. 

@inoue-a Thank you for your PR submission it is greatly appreciated.  For future contributions on string translations please join our unified Transfix system going forward which can be joined by emailing translate@steemit.com 
Thank you!

**Comment by roadscape** [comment]
@originated is this PR still relevant?

**Comment by roadscape** [comment]
@inoue-a could you please merge in master and resolve conflicts? Let's get this merged soon!

**Comment by inoue-a** [comment]
@roadscape resolved

**Comment by roadscape** [comment]
Moved to local branch; continued in #2675. Thanks @inoue-a!

**Pull request closed without merging**
