### PR TITLE
Updates to BadActorList.js

### PR DESCRIPTION
**Pull request by pfunks**

### CODE REVIEW

**Comment by thecryptodrive** [comment]
Please add account @pse to bad actor's list, it is sending memos to minnowbooster users requesting refunds be sent to @pse

**Comment by Kostronor** [comment]
Created #2371 for that @thecryptodrive

**Comment by gl2748** [comment]
@pfunks i see `p-funk` added here, is there a screencap / other evidence of the errant behaviour to warrant characterization as a 'bad-actor'...

**Comment by pfunks** [comment]
@gl2748 yes, the `p-funk` account was created by a known scammer and typo name squatter: https://steemd.com/@p-funk

**Pull request merged**
