### PR TITLE
Community - Place Promoted Posts within Hot and Trending

### PR DESCRIPTION
**Pull request by eonwarped**
This directly addresses comments in #1072 which suggests that it is desirable to show promoted posts interspersed with trending ones.

Here's a snapshot of what it looks like:

promotedandtrending

The change is fairly small, involving:
1. Fetching of the state of the promoted page in addition to that of trending and hot.
2. Interleaving the promoted posts with the others.
3. Style changes to mark promoted posts.

Added a few saga tests as well. It does appear it was pending some infrastructure changes, but wanted to see what you thought about this.

### CODE REVIEW

**Comment by eonwarped** [comment]
Hmm... looks like I will need to add changes to only highlight the selected posts instead of every promoted post.

**Comment by noisy** [comment]
I wrote about this few months ago as a comment to [Steemit Roadmap 2018: Community Input Requested
](https://steemit.com/roadmap2018/@steemitblog/steemit-roadmap-2018-community-input-requested#@noisy/re-steemitblog-steemit-roadmap-2018-community-input-requested-20171116t203908596z)

> ## Facts
> * no one is looking into "promoted tab"
> * "promoting tab" is not effective, therefore people are looking for more effective solutions
> 
> ## Solution?
> * Promoted content should be mixed by default into trending page
>   * fact: artificially promoted content is already mixed into trending, by voting bots, but right now it is much harder to check how many of paid votes some article got
> * starting from 2nd or 3rd spot on trending, every 10-15 entry on trending should be filled by promoted content
> * with only a few spots on trending page, people will get proportional number of displays (impressions) in comparison to amount of SBD spent on promotion
>   * this mean, that if @fknmayhem would spend 50SBD on promotion, and @steevc would spend 100 SBD on promotion, then article of @steevc will appear twice as often on trending page as article of @fknmayhem
> * even with spending just 1 SBD you will have a chance to be displayed on trending page. If you will have some luck and your content will be good, some whale will vote for you!

IMO it is important... that amount spent on promotion would not translate directly to rank on trending page, but to probability of being displayed on the top of trending page.

**Comment by eonwarped** [comment]
Yes, I do like the idea of a probabilistic selection system, but something like that would need backing infrastructure (hivemind?). However, I don't think that this would hamper the current trending landscape. I'm not aware of how the promoted values decay in value though, so not sure how long a post would be stuck there with the current proposal.... In any case, if it's desired, this would allow steemit to put it in easily.

**Comment by roadscape** [comment]
Shelving this for now, post lists will be undergoing significant changes w/ communities rollout, and such a feature could be more easily implemented on the new backend APIs.

**Pull request closed without merging**
