### PR TITLE
(WIP) Adding Table of Contents to FAQ Page - Feedback Requested

### PR DESCRIPTION
**Pull request by TimCliff**
@pfunks and I are are working on changes to the FAQ page to add a lot of additional content. As part of the changes, we will be adding a table of contents. The purpose of this PR is to get feedback on the TOC part of the change, so that we can determine the correct conventions/format/structure/style to follow for the larger FAQ.

The TOC will be at the top of the page, and will have links to each question:

image

The questions will be organized into categories, but for the purpose of this PR I just used fake/sample categories. This is so I didn't have to move the questions around, which would have introduced a bunch of unnecessary differences to the file. (In the final version, we will decide on actual categories and move the questions around to be in the right ones.)

Clinking on a link brings the user to that question in the TOC. At the bottom of each question's content, there is a link back to the TOC:

image

Please provide feedback on the changes.

### CODE REVIEW

**Comment by TimCliff** [comment]
I am mainly looking for feedback on the following items:
- Is the solution to use anchor links an acceptable way to add the TOC to the page?
- What naming convention should I use for the anchor links?
- Is using the `padding-top: 90px;` CSS class an acceptable way to deal with the shift that occurs on the page due to the top level menu?

**Comment by valzav** [comment]
@TimCliff everything looked good to me so I've merged it, but didn't notice "sample categories", could you add real categories via another PR? 
Aside note: please use rem units instead of px.

**Comment by TimCliff** [comment]
Sure, will do

**Comment by TimCliff** [comment]
@valzav - I wasn't able to come up with a good set of categories with the content that was there currently. It would have ended up with lots of categories with only one item, or several very generic ones with tons of semi-related items. It made the most sense to just remove the categories for now until we can add more content to balance them out.

**Pull request merged**
