### PR TITLE
add a wrapping div to any content containing an iframe

### LINKED ISSUE #2260: another HtmlReady xmldom iframe bug
see examples in https://github.com/steemit/condenser/issues/2246#issuecomment-354626864

if a post is created with no root-level element and an iframe alongside other elements, xmldom will fail.

example, as seen at http://localhost:8080/openmic/@steembirds/steemit-open-mic-week-65-bots-bots-bots-bots-original-songs:

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/wDYBzilIg0Y" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
<h1>Bots Bots Bots Bots (lyrics)</h1>
<p>Bots bots bots bots<br>
I love those bots<br>
So predictable<br>
And dependable<br>
Bots bots bots bots</p>
<p>Sitting on the beach<br>
Don't have to check in<br>
Long Island Iced Tea<br>
My bot is always running</p>
<p>Dancing at the club<br>
Pass another Blue Gem<br>
My bot's at home<br>
Upvoting my friends</p>
<p>Bots bots bots bots<br>
I love those bots<br>
So predictable<br>
And dependable<br>
Bots bots bots bots</p>
<p>My bot never sleeps, never ever ever ever ever sleeps<br>
Upvote and repeat and repeat<br>
Beep beep beep<br>
My bot never sleeps, never ever ever ever ever sleeps<br>
Upvote and repeat and repeat<br>
Beep beep beep</p>
<p>Bots bots bots bots<br>
I love those bots<br>
So predictable<br>
And dependable<br>
Bots bots bots bots<br>
<img src="https://steemitimages.com/DQmUbN48ShLMuTwEx12dbk74sWwRZ3KdCwCnJVtzmXbG4X3/Screen%20Shot%202017-11-18%20at%202.56.08%20PM.png" alt="Screen Shot 2017-11-18 at 2.56.08 PM.png"></p>
```

### PR DESCRIPTION
**Pull request by bnchdrff**
closes #2260 

xmldom... ugh

### CODE REVIEW

**Comment by bnchdrff** [comment]
i've done some limited testing with various top-level objects, and the only tag i've found to have issues at the top level is iframe -- object, div, p, etc were all fine. i didn't see any obvious causes for this in xmldom, and also i'd tried updating xmldom's patch version from 22 to 27 (latest) with no change evident.

i agree that wrapping everything in a tag would work well -- a div works, even

**Comment by roadscape** [comment]
I wonder if the issue might be in how iframes are getting handled here: https://github.com/steemit/condenser/blob/master/src/shared/HtmlReady.js#L296

**Comment by bnchdrff** [comment]
the error happens even for a bare iframe, like `HtmlReady('<iframe></iframe>', { hideImages: hideImages })`

**Comment by roadscape** [comment]
Ugh ok.. Well condenser's editor wraps all html content (i.e. non-markdown bodies) in `<html>...</html>`.. this creates an easy heuristic and adds a single top-level element which gets stripped out before rendering. I'd suggest checking for its presence and adding if not there. Let's not use `<div>` for this because it has a higher chance of interfering with ugc.

**Comment by bnchdrff** [comment]
that makes sense to me; i'll make that change now

**Comment by bnchdrff** [comment]
alright, made the change @roadscape

**Comment by bnchdrff** [comment]
ping @roadscape

**Comment by bnchdrff** [comment]
i'm going to do a benchmark for this one; might add another endpoint to test various htmlready scenarios

**Pull request merged**
