### PR TITLE
Community - Filter Resteemed Posts from Individual User Profile Feed

### PR DESCRIPTION
**Pull request by eonwarped**
Referenced in #616 and #819, I decided to take a look at a possible angle for supporting resteem filtering in a way that would be useful for a good chunk of cases and without relying on backend filtering.

The way it is done is that in the fetch data saga, it will post-filter the data, and fetch the next portion, until the batch size is completely filled, or until an imposed max-batch-limit is reached (currently set to 10, for a total of 200 posts fetched at most for such a run).

Data fetched while in the "hide resteem" mode will essentially be thrown out, and when toggling between the modes, this PR throws out the blogs and starts from scratch again. 

Hmm... as I'm writing this I'm thinking about whether I should even just retain the data that I fetch so that when toggling to and from resteem it doesn't need to start from scratch, and that would simplify the current PR by a lot. Not sure I'm even saving much in terms of memory / GC.... I'll explore that a bit.

Here's where I put the link for now, would need a mock to guide where to place it, if we want it. Most likely needs to be pulled-right or something:

hideresteemlink

### CODE REVIEW

**Comment by eonwarped** [comment]
As I'm looking at the other, it sounds like it would be better to even introduce a filter predicate passed to the fetchData saga that can do the same behavior, retain all data, but fetch until the desired amount of filtered items is reached (or max-fetch-batch is hit).

This way it can support generic filtering like tag-based filtering.

Then again, it also seems like it would be obsolete with app-base, but I was itching to have something immediate. I understand if it the changes don't really jive with what's coming.

**Comment by roadscape** [comment]
@eonwarped would you mind adding tests for this feature? Otherwise it's looking good to go.

**Comment by eonwarped** [comment]
Added reducer tests for the new additions.

**Comment by roadscape** [comment]
Thank @eonwarped! Continues in local branch @ https://github.com/steemit/condenser/pull/3011

**Pull request closed without merging**
