### PR TITLE
#1771 support non-latin tags

### PR DESCRIPTION
**Pull request by skenan**

### CODE REVIEW

**Comment by bnchdrff** [comment]
@gl2748 this is a good one to start with -- want to add test coverage for these changes & verify?

**Comment by gl2748** [comment]
Looking at this now.

**Comment by gl2748** [comment]
@skenan   thanks for contributing!

**Comment by bnchdrff** [comment]
@gl2748 where did this leave off?

**Comment by gl2748** [comment]
@bnchdrff See:
https://github.com/steemit/condenser/compare/1771-non-latin-support?expand=1

I am going to extract testing work on `resolveRoute.js` and `TransactionSaga.js` into a separate PR as that is salvageable.
Basically until: the blockchain supports UTF-8 tags this work is blocked - furthermore there is work slated to remove categories altogether which will impact this approach.

**Pull request closed without merging**
