### PR TITLE
2153 search bar input overlap

### LINKED ISSUE #2153: top bar search input overlaps signup link & makes it unclickable
to reproduce, open up a browser window that's ~877px wide, and try clicking on the sign up button -- you'll see that your click focuses the search text input.

screenshot from 2017-12-13 16-47-57

### PR DESCRIPTION
**Pull request by gl2748**
fixes #2153
# After
## Large Screen.
screenshot from 2017-12-14 12-38-31

## Medium Screen. 
screenshot from 2017-12-14 12-37-09

## Small Screen.
screenshot from 2017-12-14 12-39-20

### CODE REVIEW

**Comment by gl2748** [comment]
@relativityboy @pkattera - ok, not sure what is meant by this, what's the 'spectacle'? the 'magnifying glass'? What is meant by 'jumping'? 

To be clear, what this does is 'only display an input element for search on large screens. On medium and small screens the behavior, is that the user clicks the 'magnifying glass' icon and is taken to the search page.

**Comment by relativityboy** [comment]
@gl2748 
> what's the 'spectacle'? the 'magnifying glass'? 
Yes.

> What is meant by 'jumping'?
As a user shrinks the browser window the input field disappears and the magnifying glass 'jumps' to the right.

This left alignment of the magnifying glass and search box may require moving it into a different section of the DOM tree.

**Comment by gl2748** [comment]
# So far.
screenshot from 2017-12-14 16-09-10

**Comment by relativityboy** [comment]
We're looking for this - 
screen shot 2017-12-14 at 3 34 50 pm

screen shot 2017-12-14 at 3 34 41 pm

FYI - To generate these screens, I moved the search parent's < li > into the `<ul class="HorizontalMenu menu show-for-medium">`

**Comment by gl2748** [comment]
# Currently.
## Large
screenshot from 2017-12-15 09-57-53
## Medium
screenshot from 2017-12-15 09-58-11
## Small
screenshot from 2017-12-15 09-58-51

**Pull request merged**
