### PR TITLE
Community - Match width of editor preview and actual post

### PR DESCRIPTION
**Pull request by quochuy**
Changing the width of editor preview to 50rem like PostFull

### CODE REVIEW

**Comment by roadscape** [comment]
@quochuy did you consider changing the editor to 50em instead? Need to check if 52em for PostFull causes any display issues, and constructing the preview is much less invasive

**Comment by quochuy** [comment]
@roadscape no I haven't tried the other way around as I feel that more space is better anyway.

I would even make it wider as 52rem renders to only 832px and I feel that there are too much empty spaces on either sides but that's another issue.

**Comment by roadscape** [comment]
@quochuy it's possible that a lot of posts are formatted to look best at the current 50em width. For this reason I think we should limit the changes to just the editor preview width. If rendered content needs to be wider let's treat it as a separate issue -- there are other concerns such as long lines can be bad for readability.

**Comment by quochuy** [comment]
@roadscape Fair enough, agreed. Will update the PR

**Comment by quochuy** [comment]
PR updated.

**Comment by roadscape** [comment]
Thanks! Moved to local PR #3297

**Pull request closed without merging**
