### PR TITLE
Added portuguese tag in Faq

### PR DESCRIPTION
**Pull request by elieltavares**
We came to the conclusion of using the tag 'portugues' to gather all speakers of the Portuguese language

### CODE REVIEW

**Comment by originated** [comment]
Sounds good to ad, I'm a but curious is it good we have some inconsistencies here and a few have the full wording? 

Perhaps we should use the standard global ISO code for all, example:

Chinese = cn
German = deutsch (should be de)
Spanish = spanish (should be es)
Korean = kr
Russian = ru
French = fr
Portuguese = portugues (should be pp)

**Comment by bycz6** [comment]
Portuguese should be "pt" instead of pp

**Comment by originated** [comment]
@bycz6 Aw yep correct, updated the list.

**Comment by TimCliff** [comment]
For new communities that are just forming, the standard global ISO code seems the obvious way to go. For the existing language communities that are already formed around a tag though (example deutsch) someone from the community will need to work on getting the members of the community to transition to the new tag.

**Comment by elieltavares** [comment]
I agree to use the 'pt' tag, because the Portuguese community is still small, because for now it is possible to change

**Comment by originated** [comment]
One concept we could consider to foster our global growth is have a legend/or easy country code picker. Either directly in the text field as they type with suggestions, more cumbersome, or something more simple under the textbox that they click with the all the codes listed(which could auto populate their tag). This could elimate user error and confusion

**Pull request merged**
