### PR TITLE
Fixes #3195 - Adds border around the components of a comment block

### LINKED ISSUE #3195: Comment layers are not visible enough
Currently, we only have this little dot showing us on which comment-level/layer we are, which is not visible enough IMO. I actually didn't know it existed, because I didn't see it until @eonwarped told me about it:

image

I would prefer to have something along the lines of this:

image

### PR DESCRIPTION
**Pull request by quochuy**
Local screenshot:
Screen Shot 2019-05-10 at 9 58 15 am

### CODE REVIEW

**Comment by economicstudio** [comment]
this looks cool!

**Comment by roadscape** [comment]
Hi @quochuy, I'm not entirely sure we want to go this route but I did want to explore your concept further. On the [`quochuy-comment-separation`](https://github.com/steemit/condenser/tree/quochuy-comment-separation) branch you will find I made the display slightly more condensed and also added theme support (now it works in night mode). However there do still seem to be some bugs, namely with partially (grayed) or fully collapsed comments. It seemed to be due to conflicting `border` rules with some classes.

**Comment by quochuy** [comment]
@roadscape ok will check that out

**Comment by quochuy** [comment]
@roadscape can you give more details about the issue you were talking about?

**Comment by quochuy** [comment]
@roadscape ahh I think I managed to reproduce the bug.

**Comment by quochuy** [comment]
@roadscape what do we do with this PR now?

**Comment by roadscape** [comment]
Time for a local PR I guess 😄#3394

**Pull request closed without merging**
