### PR TITLE
Closes #2088 FAQ update - Steem and Steemit logos use terms

### LINKED ISSUE #2088: Update FAQ question for Steem and Steemit logos terms of use
Issue for PR https://github.com/steemit/condenser/pull/1894 to update the terms of use for the Steem and Steemit logos.

### PR DESCRIPTION
**Pull request by plink01001**
The PR should not be accepted and merged without approval from @sneak or @nedsteem .

### CODE REVIEW

**Comment by plink01001** [comment]
updated changes proposed. needs new review by @sneak or @nedsteem .

**Comment by bnchdrff** [comment]
ping: @sneak @nedsteem

**Comment by bnchdrff** [comment]
ping: @sneak @nedsteem is this approved?

**Comment by plink01001** [comment]
@sneak - the change to clarify the Steem logo is the blue logo has been made. Is the PR good to go?

**Pull request merged**
