### PR TITLE
Update UserProfile.scss

### PR DESCRIPTION
**Pull request by deveerei**
Added:
    margin-left: 5%;
    margin-right: 5%;
To .UserProfile__tab_content

Reason: Fix alignment of content box on screen to middle. Current alignment is off, there's more space on the right side.

### CODE REVIEW

**Comment by bnchdrff** [comment]
@pkattera this seem ok?

**Comment by deveerei** [comment]
Yes this was already resolved. But I submitted this almost a month ago. Fix came a week or so after.

**Comment by bnchdrff** [comment]
@deveerei thanks! sorry we weren't able to get to it sooner; we appreciate your input.

**Comment by deveerei** [comment]
It's okay. You're welcome and thanks as well.

**Pull request closed without merging**
