### PR TITLE
add the simplified Chinese locales

### PR DESCRIPTION
**Pull request by skenan**

### CODE REVIEW

**Comment by skenan** [comment]
Any concern not to merge this pull request? @roadscape

**Comment by sneak** [comment]
@skenan thank you for this! :)

**Comment by skenan** [comment]
@sneak No problem. Any questions just let me know.

**Comment by skenan** [comment]
Please take a look at this one @roadscape @sneak

**Comment by gl2748** [comment]
@skenan I am going to be reviewing this as part of your work on your PR #1840 regarding issue #1771

**Comment by gl2748** [comment]
This work has been incorporated into PR #1840

**Comment by bnchdrff** [comment]
is there any reason to not just merge this one as is, before #1840? it's only a locale

**Comment by gl2748** [comment]
@bnchdrff agreed, wanna merge?

**Comment by originated** [comment]
Please merge

**Comment by bnchdrff** [comment]
is this a different dialect than #2171?

**Comment by originated** [comment]
@skenan please join our unified translations system by emailing translate@steemit.com, we need to compare this version with our other trnalsators. We need to make sure it's in sync on both

**Comment by skenan** [comment]
@originated I have already emailed to translate@steemit.com Any update?

**Comment by relativityboy** [comment]
@originated -

**Comment by originated** [comment]
@skenan Please check your email for the invite, please let me know if you don't see it.

**Comment by skenan** [comment]
@originated Thanks ! I got the email and joined the team.

**Comment by bnchdrff** [comment]
see https://github.com/steemit/condenser/pull/2171

**Pull request closed without merging**
