### PR TITLE
Add a small search input field next to the search button on the header.

### PR DESCRIPTION
**Pull request by netuoso**
## Issue
Currently users have to click the small search icon to be redirected to the search page. They then have to click the input on the search page, begin typing and press enter to see results.

## Solution
Add a search input field next to the search icon if users prefer to be more direct.

## Summary
At the moment, it is kind of a pain to search the website. We have the solution in place of the google site search link, but it isnt very user friendly. In an effort to approve the end user experience, this pull request adds a small input field next to the search icon on the header. It respects the rules of staying hidden on small screens.

## Screenshots
screen shot 2017-11-14 at 2 46 33 pm
screen shot 2017-11-14 at 2 46 13 pm

### CODE REVIEW

**Comment by pkattera** [comment]
Thanks again @netuoso – loving your work. The search page isn't user friendly right now and this is a good solution to get people to their desired destination faster.

My suggestion for bonus points is to also move the search bar over to the left hand side of the navigation. This will:
1. Keep the content find and filter items together in close proximity.
2. Avoid the non-standard right aligned text search while typing in the search input.

For example:

screen shot 2017-11-14 at 5 22 01 pm

We could also keep the border transparent until in focus will will keep the navigation UI clean.

**Comment by netuoso** [comment]
Should be easy enough! I will make the suggested changes tonight

**Comment by netuoso** [comment]
## Inactive
screen shot 2017-11-14 at 9 29 40 pm

## Focus/Hover
screen shot 2017-11-14 at 9 29 47 pm

It's getting close, still not quite there because it isn't showing up right on small/medium sized screens. Will probably just leave the right side search button for small screens. (Only really visible for a few screen sizes)

**Comment by pkattera** [comment]
Hi @netuoso – I made some small style tweaks to the search bar and themed it for night mode. Let me know what you think.

**Comment by netuoso** [comment]
@pkattera It is beautiful. I am definitely not the man to ask about CSS tricks. I meant to finish this one up today but I didn't get around to it.

Tomorrow!

(would be cool if i could add labels; in progress / ready for review .. just a thought)

**Comment by netuoso** [comment]
screen shot 2017-11-16 at 12 05 30 am

screen shot 2017-11-16 at 12 05 37 am

screen shot 2017-11-16 at 12 05 42 am

screen shot 2017-11-16 at 12 05 47 am

**Comment by gl2748** [comment]
@netuoso this is awesome stuff. Thanks!

**Comment by gl2748** [comment]
Superseded  by: https://github.com/steemit/condenser/pull/2122

**Pull request closed without merging**
