### PR TITLE
add share on reddit button

### LINKED ISSUE #2753: Community - Add Reddit share button
A lot of users like to share their Steemit posts on Reddit to attract attention from users outside the platform. There is a request to add a Reddit share button to the share links.

### PR DESCRIPTION
**Pull request by netuoso**
Pretty basic. Adds the Reddit SVG icon (greyscale) and appends it to the share_menu on PostFull.jsx.

Due to weird behavior when opening a new window for the Reddit share, the button replaces the current window.location with the required link for the Reddit share for enhanced UX. Up to suggestions on getting the Reddit share window to be properly opened and sized in a new popup window.

closes #2753 

screen shot 2018-04-23 at 6 41 56 pm
screen shot 2018-04-23 at 6 42 08 pm

### CODE REVIEW

**Comment by omicreative** [comment]
This would be fantastic as Acidyo is trying to get more Steemians to use the Steem subreddit. 
-omitaylor

**Comment by pkattera** [comment]
This passes my product review for now. We can merge pending a technical review.

Note: In general the social icons are a bit of a mess. It's something we should redesign soon.

**Comment by roadscape** [comment]
This PR is available via local branch `netuoso-2753-share-on-reddit` for testing. Implementation is clean; no need for PR-dance unless changes are required.

**Comment by roadscape** [comment]
Are there any reddit icons better matching the others' styles?

image

**Comment by pkattera** [comment]
Let's use the attached logo. 

I've attached two files (the one titled 'example' is just to show what it will look like). In production, it will be best to use to other file which doesn't have a `fill` set. By removing `fill`, we should be able to inherit the css hover state rules that the other icons have.

[logo-reddit.zip](https://github.com/steemit/condenser/files/1964998/logo-reddit.zip)

**Comment by roadscape** [comment]
Had to remove the `fill="none"` (I guess it overrides our gray-fill directive), here's how it looks:

image

**Comment by roadscape** [comment]
Continues in local branch at #2773

**Pull request closed without merging**
