### PR TITLE
auto lower case for tags instead of error

### PR DESCRIPTION
**Pull request by voorash**
Not sure if it is ok to change the event object. If not let me know and I will add code to make a copy and change the copy.

### CODE REVIEW

**Comment by voorash** [comment]
#1647

**Comment by roadscape** [comment]
Perhaps fixing input `onBlur` instead of hijacking `onChange` would be better?

**Comment by voorash** [comment]
There were two issues I ran into that led me to take this approach.  It has been a few weeks so I can't remember which was which but what eventually led me to this was one way fixed the problem but the validation error message still appeared and the other if you typed a category such as hellO then when it corrected it to hello the browser moved the cursor back to the beginning of the line after fixing it. There was also a case where if the last letter you typed was capital then it would go through.

**Comment by relativityboy** [comment]
I've played with a couple solutions. The lightest weight would be to do the transform to all lowercase on post. The second-lightest weight would be to put a preview box just below the tag input. @pkattera ?

**Comment by relativityboy** [comment]
We have a new issue ( #2061 ) that addresses this in a more user friendly way.

@voorash - thanks for working on this code, though we're not merging, it resulted in the creation of 2061, which we'll be working on in short order!

**Pull request closed without merging**
