### PR TITLE
sort comments by author reputation

### PR DESCRIPTION
**Pull request by roadscape**
Replaces #2623 by @caleblogan:

> Not sure if you want this. I thought I would just throw it up here and see what you thought.
> Suggestion post: https://busy.org/@therealwolf/feature-request-sorting-comments-by-author-reputation

### CODE REVIEW

**Comment by roadscape** [comment]
Only issue I see is inconsistent capitalization:

image

Otherwise this feature works great.

**Comment by bnchdrff** [comment]
that's a pre-existing bug though; let's throw in a `text-transform` to fix it in this PR though

**Comment by bnchdrff** [comment]
(i'm doing it now)

**Comment by roadscape** [comment]
👌it looks like the FoundationDropdownMenu itself will need a new class applied to it, right now it's all generic

**Comment by bnchdrff** [comment]
created a new set of translatable strings for the sort order options, which lets us capitalize them without weird styling, and also makes sense for providing context to translators

**Pull request merged**
