### PR TITLE
non-posting key login warning

### PR DESCRIPTION
**Pull request by roadscape**
cherry-picked https://github.com/steemit/condenser/pull/3215 onto `master`

### CODE REVIEW

**Comment by roadscape** [comment]
Tested, works great.

**Comment by wehmoen** [comment]
Can we please have an option to disable this warning?

**Comment by jredbeard** [comment]
@wehmoen this change is to prepare users for not being able to use anything but a posting key on steemit.com in the near future - login with a master password or active key will soon be disabled.

check out recent blogposts from @steemitblog for more information regarding the condenser wallet split

**Comment by wehmoen** [comment]
I guess this is the time to install my own condenser which has all the features in one installation.

**Pull request merged**
