### PR TITLE
actually run prettier

### LINKED ISSUE #2091: run prettier via pre-commit
the last step of #2081 

depends on #2090

- [x] run Prettier over the codebase
- [x] Make sure Prettier doesn't break anything
- [x] make Prettier a precommit hook

we already have `pre-commit` so this is nice and easy to do

### PR DESCRIPTION
**Pull request by bnchdrff**
closes #2091 

removes our current pre-commit dependency in favor of husky & lint-commit
adds precommit hook to prettify any staged files
updates our whole codebase to match our prettier standard

### CODE REVIEW

**Comment by roadscape** [comment]
should it ignore `json` files?

**Comment by bnchdrff** [comment]
@roadscape it's only formatting json files in src, and it will only apply json appropriate formatting (will not remove quotes around prop names f.ex)

**Comment by bnchdrff** [comment]
if a json file is in src, it's probably meant for humans to look at it :) @roadscape objections or no?

**Comment by roadscape** [comment]
@bnchdrff it should be fine unless it causes a PITA for the outstanding i18n PR's. and does 4 spaces make as much sense for json?

**Comment by goldibex** [comment]
This is a non-issue. Please accept thr results of formatting the JSON and
move on.

**Comment by roadscape** [comment]
otherwise the few dozen files I checked looked good. almost everywhere it's a definite improvement.

**Pull request merged**
