### PR TITLE
Fix App query PropType and object compare

### LINKED ISSUE #2635: App component expects query prop to be string, but it's an object
introduced in #2629 

```
  <-- GET /
Warning: Failed prop type: Invalid prop `query` of type `object` supplied to `App`, expected `string`.
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext
    in IntlProvider (created by Translator)
    in Translator (created by Connect(Translator))
    in Connect(Translator)
    in Provider

```

### PR DESCRIPTION
**Pull request by caleblogan**
fixes #2635 

- use lodash isEqual to compare query object
- change query propType from string to object

### CODE REVIEW

**Comment by teukumuhas** [comment]
(Y)

**Comment by bnchdrff** [comment]
since we're only worried about re-rendering if the sort param is changed why not specifically check for it rather than doing a potentially expensive deep equals? also i'm curious, when you did your original work, why did you choose to re-render App rather than one of the lower-down-the-tree components like PostFull? (i didn't look into this deeply)

**Comment by caleblogan** [comment]
I didn't see `withRouter` or something similar in the codebase so I was trying to avoid that. I pushed another commit as a proposed fix using `withRouter`.

**Comment by caleblogan** [comment]
I notice there is a SagaCancellationException for `watchLocationChange` thrown sometimes using withRouter. Is there a better way to get the location than `withRouter`?

**Comment by bnchdrff** [comment]
@caleblogan check out my commit i pushed to your branch -- i think this is a nice way of handing it!

**Comment by bnchdrff** [comment]
(we aren't using react router in the most kosher way in condenser and it makes work like this a little difficult!)

**Comment by caleblogan** [comment]
That looks good! Thanks for working with me, learning a lot.

**Pull request merged**
