### PR TITLE
use https not wss

### LINKED ISSUE #2194: change default config to use HTTPS not WSS
this will make local dev less error-prone (see #1853)

### LINKED ISSUE #2299: Receiving "Unhandled rejection Error: connect ETIMEDOUT" error
I just installed this repo following the instructions and everything builds correctly but I'm receiving these timeout errors when trying to view http://localhost:8080/. Doesn't matter whether I try dev or production mode. The errors are pointing to steem-js.
  
Dev mode errors - https://gist.github.com/randytorres/846024e4e7e62d098f99eb90e8557ca4

Production mode errors - 
`Unhandled rejection Error: connect ETIMEDOUT 54.86.108.212:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)`

### PR DESCRIPTION
**Pull request by bnchdrff**
closes #2194
closes #2299

change default config to use https connection to steem api server

### CODE REVIEW

**Comment by goldibex** [comment]
the change looks good. please test this extensively in staging to make sure it doesn't break everything though

**Comment by bnchdrff** [comment]
@jredbeard please take a peek at this

**Comment by bnchdrff** [comment]
@jredbeard ping

**Comment by jredbeard** [comment]
@bnchdrff this needs to be https://api.steemit.com - steemd.steemit.com is going to be deprecated in 5 days

**Comment by bnchdrff** [comment]
cool, changed it!

**Pull request merged**
