### PR TITLE
Community - add border around comment blocks

### LINKED ISSUE #3195: Comment layers are not visible enough
Currently, we only have this little dot showing us on which comment-level/layer we are, which is not visible enough IMO. I actually didn't know it existed, because I didn't see it until @eonwarped told me about it:

image

I would prefer to have something along the lines of this:

image

### PR DESCRIPTION
**Pull request by roadscape**
From @quochuy #3332:

> Fixes #3195
>
> Local screenshot:
> Screen Shot 2019-05-10 at 9 58 15 am

(note, screenshot is slightly outdated)

### CODE REVIEW

**Comment by roadscape** [comment]
For evaluation - 

Old
image

New
image

**Comment by quochuy** [comment]
Looks good in night mode :-D

**Comment by JonathanPorta** [comment]
For reference, here are the non-night mode versions:

Old
image

New
image

**Comment by quochuy** [comment]
@JonathanPorta thanks for the feedback. I'll give a look at the mobile stylesheet and see if I can improve it.

**Comment by quochuy** [comment]
@JonathanPorta check this PR https://github.com/steemit/condenser/pull/3408

**Comment by quochuy** [comment]
Copying the screenshots from #3408 

Mobile:
Screen Shot 2019-06-19 at 8 11 09 am

Desktop (updated):
Screen Shot 2019-06-19 at 8 39 01 am

**Comment by roadscape** [comment]
Woot! Thanks @quochuy!

**Pull request merged**
