### PR TITLE
GDPR 1197

### PR DESCRIPTION
**Pull request by nynhex**

### CODE REVIEW

**Comment by Smittyvb** [comment]
This is a list of usernames. Post links should go in the DMCA list.

**Comment by Smittyvb** [comment]
Your first commit was correct, your second commit moved it to the wrong file.

**Comment by jredbeard** [comment]
The correct fix for this is to just have the username in the GDPR list instead of a URL.

**Comment by nynhex** [comment]
@Smittyvb @jredbeard fixed

**Pull request merged**
