### PR TITLE
#proposal 86 hide resteems

### PR DESCRIPTION
**Pull request by the-gorilla-steem**
These changes add "Hide Resteems" functionality to all Friends Feeds and improves the layout of the Community Banner on mobile devices (when there are a large number of subscribers or rewards).

@ety001 - Could you deploy to steemitdev please?

### CODE REVIEW

**Comment by ety001** [comment]
@the-gorilla-steem 
Hi, it has been deployed. Please test it.

**Comment by the-gorilla-steem** [comment]
@ety001 
Hello, it's looking good.  I have made a couple of minor adjustments - please can you redeploy, ready for a final test.

**Comment by the-gorilla-steem** [comment]
@ety001
Hello, it's looking good. I have made a couple of minor adjustments - please can you redeploy, ready for a final test.

**Comment by ety001** [comment]
@the-gorilla-steem 
Hi, it was deployed. Please test.

**Comment by the-gorilla-steem** [comment]
@ety001 - I think I'm going to spend a little time tweaking it a little more.  The functionality works as it should but I can improve its appearance so I will spend a bit of time doing that.

**Comment by the-gorilla-steem** [comment]
Hi @ety001 - adjustments made.  Please redeploy to steemitdev when you can.  Thank you.

**Comment by ety001** [comment]
@the-gorilla-steem 
Hi, it was deployed. Please test.

**Comment by the-gorilla-steem** [comment]
Thanks @ety001.  This has tested well and I'm happy for this to go live.  Thank you 👍

**Review by ety001 — APPROVED** [review]

**Pull request merged**
