### PR TITLE
Suggestion - Add Feature to Sort By Author Reputation

### PR DESCRIPTION
**Pull request by caleblogan**
Not sure if you want this. I thought I would just throw it up here and see what you thought.
Suggestion post: https://busy.org/@therealwolf/feature-request-sorting-comments-by-author-reputation

### CODE REVIEW

**Comment by roadscape** [comment]
This is great. There's a minor but annoying related bug: https://github.com/steemit/condenser/issues/2264

**Comment by pkattera** [comment]
@caleblogan Great work. I approve the feature, pending an appropriate technical review. @roadscape

**Comment by roadscape** [comment]
Aha. I see you've already fixed #2264 in https://github.com/steemit/condenser/pull/2579.

**Comment by roadscape** [comment]
PR has moved to #2634

**Pull request closed without merging**
