### PR TITLE
Community: Enable support for start timestamp on YouTube and Vimeo embeds

### LINKED ISSUE #3087: Condenser does not support timestamps on YouTube embeds
## Description
Due to the fact that Condenser parses the provided Youtube/Vimeo links and doesn't check for timestamp, when a user posts a timestamped link, the timestamp will not be factored into the generated embed.

## Pull Request
https://github.com/steemit/condenser/pull/3084

### PR DESCRIPTION
**Pull request by roadscape**
From @netuoso #3084:

> Closes #3087
> 
> ### Issue
> Condenser does not support timestamps for Youtube/Vimeo embeds
> 
> ### Description
> When a user copies a timestamped link from Youtube/Vimeo, condenser ignores this data because of a simple regex match on the url that does not take timestamp into account. This pull request contains working logic for parsing the timestamp field from Youtube/Vimeo and properly delivering it in the URL. Users simply need to copy/paste a timestamp link to use this feature.
> 
> ### Working Example
> https://condenser.steemliberator.com/music/@netuoso/greydon-square-late-night-munchies-low-technology-youtube
> 
> ### Files Changed
> - `app/components/cards/MarkdownViewer.jsx`
> - `app/components/elements/YoutubePreview.jsx`
> - `app/utils/Links.js`
> - `shared/HtmlReady.js`

### CODE REVIEW

**Comment by roadscape** [comment]
LGTM but could use test cases. Untested

**Comment by netuoso** [comment]
Oops! I added a test that proved it wouldn't affect any existing links but forgot to verify with tests the timestamp was parsed! Sorry about that @roadscape

**Comment by relativityboy** [comment]
@netuoso - we're getting a failure on circleci. [Check it](https://circleci.com/gh/steemit/condenser/7613?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). It's claiming unmet deps. If you think it's the build environment, a bump commit would jog it.

**Comment by relativityboy** [comment]
@netuoso - whichever is easier for you. FYI, we just brought in twitch support, so please make sure you don't break it. 

**MarkdownViewer.jsx**
```
/^([A-Za-z0-9\?\=\_\-]+) (youtube|vimeo|twitch) (\d+) ~~~/
```

**Comment by netuoso** [comment]
@relativityboy ok, it doesnt have a twitch related test so im going to add one to ensure i dont break anything related to it. once i reverse the twitch code and decipher the format it expects

**Comment by netuoso** [comment]
@relativityboy this can be closed in favor of https://github.com/steemit/condenser/pull/3096

**Comment by roadscape** [comment]
Closing in favor of https://github.com/steemit/condenser/pull/3096

**Pull request closed without merging**
