### PR TITLE
1386 1595 post scrolling bugs

### PR DESCRIPTION
**Pull request by gl2748**
# Refs
#1386 
#1595

# Mobile - iOS Safari.
steem_scrolling_2

### CODE REVIEW

**Comment by sneak** [comment]
This is exciting.  @valzav pointed out that this is a much better solution (using well-maintained community libraries, vs rolling our own) than we had.  Will be happy to get this merged in.

**Comment by gl2748** [comment]
@sneak @valzav 
Agreed, there is one issue with this implementation however.

When you press 'Back' on mobile, the scroll position of the underlying PostList is not restored. I've been trying to wrap my head around a fix.

1. the react-bootstrap [Modal](https://react-bootstrap.github.io/react-overlays/#modals) component is working as designed in that the focus is restored to the correct element on the PostList. If you use the 'esc' key the modal is closed and the correct position is also restored, I think  this is a function of the browser however rather than the Modal component.

2. The question is how to get a fast scroll to happen to this element ... after a user presses 'Back'? Open to suggestions. This functionality is currently working on the current implementation, if anyone knows how that works, it shouldn't be too hard to re-implement here.

**Comment by sneak** [comment]
FYI this also affects the close X in the top right of the post modal when viewing a post over a list view.

**Comment by valzav** [comment]
@gl2748, I would suggest to comment out useScroll in UniversalRender.jsx and see whether issue #1 goes away or not

**Pull request closed without merging**
