### PR TITLE
redirect pick_account to new faucet

### LINKED ISSUE #2501: Old signup url give not found error
I see the faucet is live on steemit.com we may want to redirect `https://steemit.com/pick_account` to the new faucet url, most of 3p apps redirect users to this url for signup and now it show “not found” error.

### PR DESCRIPTION
**Pull request by bnchdrff**
closes #2501

### CODE REVIEW

**Comment by gl2748** [comment]
no nginx here?

**Comment by bnchdrff** [comment]
nope we can do it right here in koa.

**Comment by gl2748** [comment]
Ok then can we delete that code?

**Comment by gl2748** [comment]
Also don't we have a utACK pact?

**Comment by bnchdrff** [comment]
which code can we delete? also yes, i am guilty of violating the utack pact!

**Comment by gl2748** [comment]
The stuff in Resolve Route for 'create_account'. This update to the koa router only targets 'pick_account' i think 'create_account' is also used by others:
https://github.com/search?utf8=%E2%9C%93&q=%22steemit.com%2Fcreate_account%22&type=Code

**Comment by bnchdrff** [comment]
we're leaving the post-step-1 parts in place to give people who've already started the account creation process a chance to finish

**Comment by gl2748** [comment]
Ah alright.

**Pull request merged**
