### PR TITLE
Changed Steemit Chat references and links to Steem Chat

### PR DESCRIPTION
**Pull request by voorash**

### CODE REVIEW

**Comment by sciborg** [comment]
Hi, I am owner of Steem.chat and we are transitioning Steemit.chat over to Steem.chat. Ned is aware of this.
Look forward to the future of Steem and Steemit :)

**Comment by pkattera** [comment]
@voorash Can you please attach a quick screenshot of the new image upload functionality.

**Comment by voorash** [comment]
Those changes were not supposed to be part of this pull request.  Something strange happened in Atom. I will upload a screenshot in a second though in the event you want to bundle them

**Comment by pkattera** [comment]
@voorash Please don't bundle into this one. Let's just add a screenshot to #2595. Cheers!

**Comment by voorash** [comment]
snap

**Comment by voorash** [comment]
Ok, So will the changes to this pull request just be ignored.

**Comment by voorash** [comment]
Ok, I got the changes that shouldn't have been in there out.  Should be good to ge

**Comment by voorash** [comment]
Changes to side panel in condenser master broke my changes so I have updated now to match. Please review and merge.

**Pull request merged**
