### PR TITLE
Fixes tiny text field bug on small screens

### PR DESCRIPTION
**Pull request by sirrius-a-b**
Fix for issue: #1520 ( and it's duplicate #1930 )

Changes I made:
- modified the grid CSS classes for promotion popup from `small-4` to `small-6 large-4`

So that the amount section has it's width set to 50% on small screens, but on large screens the width will remain as it is now.

Here is how it looks with this change on different screen sizes:

### 360px
promote-360px

### 480px
promote-480px

### 800px
promote-800px

### 1024px
promote-1024px

### CODE REVIEW

**Comment by pkattera** [comment]
Thanks @sirrius-a-b – this is certainly an improvement. How about also setting a 'min-width' as well to cover it for all the smaller screens? 

.PromotePost .input-group-field { 
  min-width: 120px;
}

**Comment by sirrius-a-b** [comment]
Hey @pkattera thanks for looking over my PR.

I agree that on screens smaller than 360px, namely 320px, the input field gets smaller. For this I modified the classes to be `small-7 medium-5 large-4`. This should cover all screens larger than 320px :)

I do not think that we should force a `min-width` there because on small screens this will overflow out of the responsive CSS grid classes. Should we not try to use the CSS grid classes everywhere we can and only force widths in the most extreme cases?

Here is how this looks with the new commit:

### 320px
promote2-320px

### 360px
promote2-360px

### 480px
promote2-480px

### 800px
promote2-800px

### 1024px
promote2-1024px

**Comment by pkattera** [comment]
Thanks @sirrius-a-b – this looks fine to me. 

ps. In terms of 'min-width', you're right about it potentially causing overflows and scrollbars etc. However, in general, if the min-width of the whole item is less than '200px', I'm not too concerned.

**Comment by gl2748** [comment]
Merged:
https://github.com/steemit/condenser/pull/2130/commits/eca8a9340dd1fcd997c2e4ae735aeeea654c75ad

**Pull request closed without merging**
