### PR TITLE
Quochuy notification filters

### PR DESCRIPTION
**Pull request by gl2748**

### CODE REVIEW

**Comment by gl2748** [comment]
@Benson0224 this is a PR against Master for: https://github.com/steemit/condenser/pull/3743
Please review, once approved it can be merged.

**Comment by Benson0224** [comment]
> #3743

i am sorry that i don't have approval access, let me check with team.

**Comment by Benson0224** [comment]
@gl2748  please submit PR to "develop" branch instead of master.  team will check and look it on "develop" branch.

**Comment by gl2748** [comment]
@Benson0224 ok...

**Pull request merged**
