### PR TITLE
Improve verbiage of delegation on steem power, include username in ve…

### PR DESCRIPTION
**Pull request by originated**
…rbiage for clearer understanding

### CODE REVIEW

**Comment by roadscape** [comment]
Unless something in the logic changed, `delegated_steem` can be positive or negative, depending on if you are delegator or delegatee. I guess it's more common to be delegated *to* but I wonder if we need to take it into account.

**Comment by goldibex** [comment]
@originated please address merge conflicts and we'll merge

**Comment by bnchdrff** [comment]
@originated ping

**Comment by originated** [comment]
@bnchdrff got it handling conflicts

**Comment by bnchdrff** [comment]
@originated can you pull in the changes from https://github.com/steemit/condenser/pull/1708 into this branch while you work on the rebase?

**Comment by bnchdrff** [comment]
also note that we should be translating the strings passed to `<Tooltip>`

**Comment by bnchdrff** [comment]
i've cherrypicked @dittaeva's tooltip change in, wanna take it from there @originated ?

**Pull request merged**
