### PR TITLE
Community - Tag Steemit employees and SM accounts as such (#2776)

### LINKED ISSUE #2776: Create a tag for Steemit employees
moved from https://github.com/steemit/conveyor/issues/31

As a user, 
I want to be able to see when posts and comments have been made by people at Steemit Inc,
so I can verify that the information can be trusted.

-----------------

This new tag can be assigned to Steemit employees and contractors.

This will enable us to:
- Test new features in production (alongside our new feature flags)
- Add a badge / insignia to employee usernames and profile pages denoting their association with Steemit Inc.
- Possibly create functionality in the future which helps employees adhere to the new code of conduct rules

### PR DESCRIPTION
**Pull request by Smittyvb**
Adds a "Steemit Team" tag to Steemit employees, beside their username, on their posts and profile:

Steemit Team tag on list of posts
Steemit Team tag under post title
Steemit Team tag on profile

I might have missed some Steemit employees on ``EmployeeList.js``. Is there a way I can get a full list of them?

Closes #2776.

### CODE REVIEW

**Comment by pkattera** [comment]
@Smittyvb Thanks so much for this contribution! It's a feature that we've wanted for a while.

I'm running this by our design team—it's possible that we may make some minor CSS tweaks to this before merging.

**Comment by Smittyvb** [comment]
Any design updates on this?

**Comment by roadscape** [comment]
@Smittyvb could we change this to a generalized "affiliation" map? We can start out with just `Steemit` labels but it would allow us to expand in the future.. e.g.

```
{'ned': 'steemit',
 'andrarchy': 'steemit',
 'aggroed': 'steemmonsters'}
```

**Comment by Smittyvb** [comment]
@roadscape I changed it to use an ``AffiliationMap``. Right now it supports ``steemit``, for Steemit employees, and ``sm``, for Steem Monsters. Here's what a Steem Monsters account looks like after the PR (Steemit employees still look the same as above):
image

**Comment by roadscape** [comment]
Thank you! Local PR: #3341

**Pull request closed without merging**
