### PR TITLE
Add Korean language translation pack

### PR DESCRIPTION
**Pull request by ianpark**
Add Korean language translation pack with the minimal (but enough for now) set of translation. This work will make the UI useable enough for the Koreans who do not understand English so that I expect more Korean people will be joining which will definitely help Steemit ecosystem to grow.

The entire translation will be done with the Korean community members. Our community will vigorously co-work to make the translation as fluent as possible. I will drive the process.

**Regarding the codeclimate check failure, it's already there. I copied src/app/locales/counterpart/fr.js to src/app/locales/counterpart/ko.js as the other language packs have the same files.**

From @ianpark, steemit.com/@asbear

### CODE REVIEW

**Comment by ianpark** [comment]
Could someone please review this change?

**Comment by Jolly-Pirate** [comment]
Korean country code is kr, not ko.

**Comment by jnordberg** [comment]
Korean language code is `ko` as in `ko-KR`

**Comment by valzav** [comment]
@ianpark your PR looks good to me. I've created korean_translation branch, could you please re-submit your PR into this branch instead of master - this way we will be able to test in dev env.

**Pull request merged**
