### PR TITLE
Community - esteem:// protocol support

### PR DESCRIPTION
**Pull request by feruzm**
This will sanitize and allow links with `esteem://`

### CODE REVIEW

**Comment by roadscape** [comment]
@feruzm is this still relevant? Can eSteem leverage the `steem://` protocol or is there some fundamental different?

**Comment by feruzm** [comment]
@roadscape yes, we have support for both `steem://` and `esteem://`. This PR adds `esteem://` because if user has Vessel and eSteem on same desktop machine it doesn't know what app to open and there is no way to choose default as well. But for mobile devices it is bit different story because user is given option to open with app of their choice.

**Comment by roadscape** [comment]
Hi @feruzm is this still relevant?

**Comment by roadscape** [comment]
Local PR: #3323

**Pull request closed without merging**
