### PR TITLE
Community - Add Spee.ch support to Condenser

### PR DESCRIPTION
**Pull request by kodxana**
With this pull request I want to add support for videos from Spee.ch condenser.

If this PR need some changes just tell me :)

### CODE REVIEW

**Comment by tzarebczan** [comment]
Hey Steemit team, would appreciate a review and some help on getting this integrated :)

**Comment by tzarebczan** [comment]
@kodxana can you look into the syntax issues from the build logs?

**Comment by tzarebczan** [comment]
Would appreciate a code review now that the builds are passing :)

**Comment by roadscape** [comment]
Hi @kodxana, I am closing this for now. Please open a new PR if you decide to pick this back up. Thanks!

**Pull request closed without merging**
