### PR TITLE
Add missing namespace to 'currently collecting' translation key

### PR DESCRIPTION
**Pull request by stephanmullerNL**
Fixes https://github.com/steemit/condenser/issues/1703

### CODE REVIEW

**Comment by sneak** [comment]
looks great!  Thank you so much @stephanmullerNL! :)

keep 'em coming!

**Comment by goldibex** [comment]
I'll merge and stage this when ready.

**Comment by bnchdrff** [comment]
looks like these changes have been applied to `master` already... good to close?

**Comment by bnchdrff** [comment]
this was fixed in https://github.com/steemit/condenser/commit/d3791fc3

**Pull request closed without merging**
