### PR TITLE
Remove redundant Strict-Transport-Security response header

### PR DESCRIPTION
**Pull request by Gandalf-the-Grey**
Fixes: #1985

### CODE REVIEW

**Comment by sneak** [comment]
or rather the frontend proxy should only add it if it does not exist. this way someone running condenser even without a reverse proxy is still protected.

**Comment by Gandalf-the-Grey** [comment]
unfortunately wouldn't be protected because condenser by default listen on 8080 without TLS and [in such case this header is ignored anyway](https://tools.ietf.org/html/rfc6797#section-8.1)
but actually because of that we can leave it as it is on condenser if we assume that frontend proxy would override it instead of duplicating

**Comment by sneak** [comment]
i'm sold.  do it on the TLS terminator.

**Comment by bnchdrff** [comment]
@Gandalf-the-Grey to confirm, this branch does not require any changes to `sdc-frontend` & can be deployed now?

**Comment by Gandalf-the-Grey** [comment]
yes, changes to `sdc-frontend` [was already made](https://github.com/steemit/sdc-frontend/pull/21)

**Pull request merged**
