### PR TITLE
Convert GoogleAd to GptAd

### PR DESCRIPTION
**Pull request by rjungemann**

### CODE REVIEW

**Comment by KINGdotNET** [comment]
Hi testing the google adsense. Is this correct config in default.json?
  "google_ad_enabled": true,
  "google_ad_test": null,
  "google_ad_client": "ca-pub-5......375",

I'm getting an error when I run  "yarn run production".

**Comment by Smittyvb** [comment]
@KINGdotNET could you post the error?

**Comment by KINGdotNET** [comment]
This is the error when I run "yarn run production"

condenser/node_modules/config/lib/config.js:925
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^
Error: Cannot parse config file: '/home/yehey/condenser/config/default.json': SyntaxError: Unexpected token # in JSON 
at position 2380
    at Config.util.parseFile (/home/yehey/condenser/node_modules/config/lib/config.js:925:11)
    at /home/yehey/condenser/node_modules/config/lib/config.js:696:28
    at Array.forEach (<anonymous>)
    at /home/yehey/condenser/node_modules/config/lib/config.js:692:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/home/yehey/condenser/node_modules/config/lib/config.js:691:13)
    at new Config (/home/yehey/condenser/node_modules/config/lib/config.js:122:27)
    at Object.<anonymous> (/home/yehey/condenser/node_modules/config/lib/config.js:1749:31)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
error Command failed with exit code 1.

**Comment by KINGdotNET** [comment]
How do I keep the Adsense ON all the time, even when a user is logged in?

**Pull request merged**
