### PR TITLE
#proposal 86 communities redesign

### PR DESCRIPTION
**Pull request by the-gorilla-steem**
Changes to the community pages:
* Introduction of graphical banner 
* Additional settings to allow community admins to customise the community's avatar and cover image
* Collapsable carousel for pinned posts
* All translations for Communities Section

### CODE REVIEW

**Review by ety001 — APPROVED** [review]

**Comment by ety001** [comment]
@the-gorilla-steem Hi, this PR has been deployed on dev environment. https://steemitdev.com .
Please test it.

**Comment by only-dev-time** [comment]
Also deployed to steemit.moecki.online for testing.

**Comment by the-gorilla-steem** [comment]
@ety001 - Everything's looking and working as I'd expect.  Please can you do what needs to be done to get it live?

**Comment by ety001** [comment]
> @ety001 - Everything's looking and working as I'd expect. Please can you do what needs to be done to get it live?

I'll let it online later.

**Comment by ety001** [comment]
@the-gorilla-steem 
Hi, it has been deployed.

**Pull request merged**
