### PR TITLE
Add a modal showing QR codes for public/private keys in permissions tab

### PR DESCRIPTION
**Pull request by svk31**
A simple modal showing the public or private keys as a QR code so that mobile apps can scan it for easy migration. Triggered by clicking the QR image on the left of each key.

image

### CODE REVIEW

**Comment by valzav** [comment]
It would be nice to implement import/login via QR code. E.g. I want to login on my phone using QR displayed in desktop browser.

**Comment by svk31** [comment]
Oh you're right, I was just thinking  about this in the context of migrating to 3rd party apps but it could be useful for mobile users of Steemit too of course! I'll have a look and see if I can add that too.

**Comment by Transisto** [comment]
Wow fast, hanks for that, What I originally had in mind was to approve an action by scanning a printout of my active key.  I guess that's coming next.

**Comment by feruzm** [comment]
Thanks for adding this... Next version of eSteem will have support for QR reading of keys on password field ;)

**Pull request merged**
