### PR TITLE
update redux saga to v0.16.0

### PR DESCRIPTION
**Pull request by gl2748**
There is some debate over the best way to test Redux-Saga.

I have been frustrated with [writing unit tests for them](https://github.com/steemit/condenser/pull/2140/files#diff-5842cb9a8b07e8c503a252d37680ec6b). Updating Redux-saga will let me try a more general integrative approach -
https://github.com/jfairbank/redux-saga-test-plan

As well as allowing for a concise TDD for future Sagas.

### CODE REVIEW

**Comment by bnchdrff** [comment]
i'm going through the redux-saga release logs to make sure we aren't missing anything big

**Comment by gl2748** [comment]
Yes there is 1.0.0 in beta. That might be the bigger issue but getting to 0.16.0 will help...

**Comment by bnchdrff** [comment]
our sagas aren't compatible with this update; i am unable to log in, for example. i think we should postpone this work until there's a very clear reason to update.

**Comment by bnchdrff** [comment]
closing this for now, see https://github.com/steemit/condenser/issues/2175

**Pull request closed without merging**
