### PR TITLE
remove htmlready console.error call

### LINKED ISSUE #2178: htmlready test error needs explanation
HtmlReady generates an error when tests are being run against it. 
`TypeError: Cannot read property 'prefix' of null`

This thrown error needs to be accounted for; with a test that triggers it and explains why it's 'ok', or the error needs to be eliminated.

### PR DESCRIPTION
**Pull request by bnchdrff**
closes #2178

this call is not needed

### CODE REVIEW

**Comment by relativityboy** [comment]
Just saw @bnchdrff's comment on #2187 
> HtmlReady never receives non-html content;

**Comment by bnchdrff** [comment]
i understand the original author's instinct to use a try..catch block; the xmldom parser could concievably have weird errors and it's a reasonable stopgap to return the original html if a problem comes up. on the flipside it could be more secure to display nothing in that case.

changing that behavior is outside the scope of this PR.

**Comment by roadscape** [comment]
Please tag me on any HtmlReady changes!

**Comment by roadscape** [comment]
If this is the case that was causing the error:

```
    it('should return plain text without html unmolested', () => {
        const teststring = 'teststring lol';
        expect(HtmlReady(teststring).html).to.equal(teststring);
    });
```

Why is this one fine:
```
     it('should detect only valid mentions', () => {
         const textwithmentions =
             '@abc @xx (@aaa1) @_x @eee, @fff! https://x.com/@zzz/test';
         const res = HtmlReady(textwithmentions, { mutate: false });
         const usertags = Array.from(res.usertags).join(',');
         expect(usertags).to.equal('abc,aaa1,eee,fff');
     });
```

If I'm looking at it right, the comment above the log line is incorrect and it's probably referring to `XMLSerializer.serializeToString`.

**Comment by roadscape** [comment]
Confirmed; full trace:
```
     TypeError: Cannot read property 'prefix' of null
      at Document.nodeSerializeToString [as toString] (node_modules/xmldom/dom.js:920:22)
      at XMLSerializer.serializeToString (node_modules/xmldom/dom.js:914:31)
      at exports.default (src/shared/HtmlReady.js:109:39)
      at Context.<anonymous> (src/shared/HtmlReady.test.js:97:16)
```

Why would `serializeToString` fail on a DOM Document?
```
Document {
  implementation: { _features: {} },
  childNodes:
   { '0':
      Text {
        ownerDocument: [Circular],
        data: 'teststring lol',
        nodeValue: 'teststring lol',
        length: 14,
        previousSibling: null,
        nextSibling: null,
        parentNode: [Circular] },
     length: 1 },
  doctype: null,
  firstChild:
   Text {
     ownerDocument: [Circular],
     data: 'teststring lol',
     nodeValue: 'teststring lol',
     length: 14,
     previousSibling: null,
     nextSibling: null,
     parentNode: [Circular] },
  lastChild:
   Text {
     ownerDocument: [Circular],
     data: 'teststring lol',
     nodeValue: 'teststring lol',
     length: 14,
     previousSibling: null,
     nextSibling: null,
     parentNode: [Circular] },
  _inc: 2 }
```

**Comment by bnchdrff** [comment]
@roadscape i think the issue is that it fails when the input is not valid xml, i.e. a text string

**Comment by bnchdrff** [comment]
the established behavior of HtmlReady is to output the original string if the xml parser throws; when i wrote the test suite i added in a bit to cover this behavior but not the `console.warn` output

**Comment by roadscape** [comment]
It doesn't seem like a case we should silence; if anything we should reraise the exception. Especially if all code paths are "supposed" to provide proper HTML input. I overlooked this pattern when writing the 'should detect only valid mentions' test, so really it seems that test should be failing.

**Comment by bnchdrff** [comment]
it def. seems like we should throw & not output the un-readied html if xmldom has an error. not sure why it was written this way.

**Comment by roadscape** [comment]
> This suggests we shouldn't have the try-catch block at all.

^ I'm thinking this is the best solution for now. If the usages are audited and this should never happen then we need to have it fail loudly if it does.

**Pull request closed without merging**
