### PR TITLE
Adding google schema for Author and publisher

### PR DESCRIPTION
**Pull request by gl2748**
Supersedes: #2170

### CODE REVIEW

**Comment by relativityboy** [comment]
Needs an issue describing why we're adding google schema.
Issue also needs to state why we're assigning Author and publisher.

```
publisher: {
                   '@id': `https://${APP_DOMAIN}/@${author}`,
               },
               author: {
                   '@id': `https://${APP_DOMAIN}/@${author}`,
               },
....
```

**Comment by sneak** [comment]
All pull request description/body fields must begin with a line that says "Closes #x", where x is an issue number.  Please resubmit.

**Comment by DennisAlund** [comment]
There is no issue for PR #2170 since the contribution guidelines states that I shouldn't open an issue for an enhancement. I figured that it wasn't a bug since nothing is broken, just not as complete as it could be.

Instead I wrote a couple of articles about it on steemit where the issue was instead intended to invite for discussion: 

 - https://steemit.com/utopian-io/@dennisalund/proposing-some-boost-to-steemit-seo-schema-markup
 - https://steemit.com/utopian-io/@dennisalund/looking-for-an-seo-expert-to-help-improving-steemit-schema-markup

Please consider to open #2170 again

**Comment by gl2748** [comment]
@DennisAlund  don't worry too much about #2170, your work is still alive and well and we'll work on incorporating it. For the time being there's going to be a discussion on Google SEO and schema here:
https://github.com/steemit/condenser/issues/2183

**Comment by DennisAlund** [comment]
Ok, thanks. I'll keep following the progress to see if there's anything that I can jump in and help with.

**Comment by relativityboy** [comment]
@DennisAlund - indeed. We definitely appreciate your efforts.

**Pull request closed without merging**
