### PR TITLE
Header dropdowns

### PR DESCRIPTION
**Pull request by svk31**
Adds a new 'Submit story' icon to the header for mobile:

image

Adds icons to the User profile dropdown menu:

image

Organizes the Hamburger dropdown menu in and changes the wording of some of the links.

image

### CODE REVIEW

**Comment by TimCliff** [comment]
I like it! Would be good to change all the hamburger links to use consistent capitalization - "Quick Start Guide".

**Comment by svk31** [comment]
Good point, will fix.

**Comment by mcifani** [comment]
Good update with the icons.  The breakup in the hamburger menu is good albeit getting a big long.

**Comment by svk31** [comment]
Yea I agree it's getting long, seems like we could remove some of those entries.

**Pull request merged**
